# Generated by Django 5.1.4 on 2025-01-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_timetable_options_alter_timetable_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
